global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]

  - job_name: "backend1"
    static_configs:
      - targets: ["backend1:5000"]

  - job_name: "backend2"
    static_configs:
      - targets: ["backend2:5000"]
